defmodule Tunez.Repo.Migrations.AddAlbumLikes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:album_likes, primary_key: false) do
      add :album_id,
          references(:albums,
            column: :id,
            name: "album_likes_album_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :like_id,
          references(:users,
            column: :id,
            name: "album_likes_like_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    create index(:album_likes, [:album_id])

    create index(:album_likes, [:like_id])
  end

  def down do
    drop_if_exists index(:album_likes, [:like_id])

    drop_if_exists index(:album_likes, [:album_id])

    drop constraint(:album_likes, "album_likes_album_id_fkey")

    drop constraint(:album_likes, "album_likes_like_id_fkey")

    drop table(:album_likes)
  end
end
