defmodule Tunez.Repo.Migrations.AddUserToArtists do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add :user_id,
          references(:users,
            column: :id,
            name: "artists_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:artists, [:user_id])
  end

  def down do
    drop_if_exists index(:artists, [:user_id])

    drop constraint(:artists, "artists_user_id_fkey")

    alter table(:artists) do
      remove :user_id
    end
  end
end
