defmodule Tunez.Repo.Migrations.AddIndexArtistFollowers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:artist_followers, "artist_followers_follower_id_fkey")

    drop constraint(:artist_followers, "artist_followers_artist_id_fkey")

    alter table(:artist_followers) do
      modify :artist_id,
             references(:artists,
               column: :id,
               name: "artist_followers_artist_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :follower_id,
             references(:users,
               column: :id,
               name: "artist_followers_follower_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:artist_followers, [:artist_id])

    create index(:artist_followers, [:follower_id])
  end

  def down do
    drop_if_exists index(:artist_followers, [:follower_id])

    drop_if_exists index(:artist_followers, [:artist_id])

    drop constraint(:artist_followers, "artist_followers_artist_id_fkey")

    drop constraint(:artist_followers, "artist_followers_follower_id_fkey")

    alter table(:artist_followers) do
      modify :follower_id,
             references(:users,
               column: :id,
               name: "artist_followers_follower_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :artist_id,
             references(:artists,
               column: :id,
               name: "artist_followers_artist_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
