defmodule Tunez.Repo.Migrations.AddUserToAlbums do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:albums) do
      add :created_by_id,
          references(:users,
            column: :id,
            name: "albums_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :updated_by_id,
          references(:users,
            column: :id,
            name: "albums_updated_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:albums, [:created_by_id])

    create index(:albums, [:updated_by_id])
  end

  def down do
    drop_if_exists index(:albums, [:updated_by_id])

    drop_if_exists index(:albums, [:created_by_id])

    drop constraint(:albums, "albums_created_by_id_fkey")

    drop constraint(:albums, "albums_updated_by_id_fkey")

    alter table(:albums) do
      remove :updated_by_id
      remove :created_by_id
    end
  end
end
