defmodule Tunez.Repo.Migrations.AddUserToArtists do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:artists, [:user_id])

    alter table(:artists) do
      remove :user_id

      add :created_by_id,
          references(:users,
            column: :id,
            name: "artists_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :updated_by_id,
          references(:users,
            column: :id,
            name: "artists_updated_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:artists, [:created_by_id])

    create index(:artists, [:updated_by_id])
  end

  def down do
    drop_if_exists index(:artists, [:updated_by_id])

    drop_if_exists index(:artists, [:created_by_id])

    drop constraint(:artists, "artists_created_by_id_fkey")

    drop constraint(:artists, "artists_updated_by_id_fkey")

    alter table(:artists) do
      remove :updated_by_id
      remove :created_by_id

      add :user_id,
          references(:users,
            column: :id,
            name: "artists_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:artists, [:user_id])
  end
end
